# Generated by Django 4.1.8 on 2023-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="gym",
            name="address",
            field=models.TextField(verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="gym",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="gym",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="gym",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="end_date",
            field=models.DateField(verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="start_date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="duration_months",
            field=models.PositiveIntegerField(verbose_name="duration in months"),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")], max_length=10, verbose_name="transaction type"
            ),
        ),
    ]
